name: small_calendar
description: Small Calendar widget. With ability to display weekday indication and some basic info about every day.
version: 0.0.3
author: ZedTheLed <kukumoraketo@gmail.com>
homepage: https://github.com/ZedTheLed/small_calendar

environment:
  sdk: ">=1.8.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  quiver: "^0.28.0"
  meta: "^1.1.1"

dev_dependencies:
  test: ^0.12.0
